-- local nnoremap = require("vice.keymap").nnoremap;
-- local _, err = require("harpoon");
-- if err then print("From harpoon: ", err) end;
-- local ui = require("harpoon.ui");
-- local mark = require("harpoon.mark");
-- local term = require("harpoon.term");

-- nnoremap("<leader>ha", function() mark.add_file() end)
-- nnoremap("<leader>he", function() ui.toggle_quick_menu() end)
-- nnoremap("<leader>ht1", function() term.gotoTerminal(1) end)
-- nnoremap("<leader>ht2", function() term.gotoTerminal(2) end)
-- nnoremap("<leader>hh", function() ui.nav_next() end)
-- nnoremap("<leader>hl", function() ui.nav_prev() end)
-- nnoremap("<leader>hj1", function() ui.nav_file(1) end)
-- nnoremap("<leader>hj2", function() ui.nav_file(2) end)
-- nnoremap("<leader>hj3", function() ui.nav_file(3) end)
-- nnoremap("<leader>hj4", function() ui.nav_file(4) end)
