require("luasnip.loaders.from_vscode").lazy_load({ paths = { "./friendly-snippets" } })
-- local ls = require("luasnip")
-- require("luasnip.loaders.from_lua").load({ paths = "./lua/snippets/"})
--
-- ls.config.set_config({
--     history = true,
--     updateevents = "TextChanged, TextChangedI",
--     enable_autosnippets = true,
--     ext_opts = {
--         [require("luasnip.util.types").choiceNode] = {
--             active = {
--                 virt_text = { { "⏺", "GruvboxOrange"}},
--             },
--         },
--     },
-- })
